---
title: "Organise data"
format: html
editor: visual
---

## Data

Data emailed to Georgia from Shok, and put in one drive

## Paths

```{r}
#| include: false

if (Sys.info()['user'] == 'galen') {
  qaelpath <- '~/../Deakin University/QAEL - WERP in house - WERP'
} else if (Sys.info()['user'] == 'Georgiad') {
  qaelpath <- '~/Deakin University/QAEL - WERP - WERP'
} else if (Sys.info()['user'] == 'georgiad') {
  qaelpath <- 'C:/Users/georgiad/Deakin University/QAEL - WERP - WERP'
} else if (Sys.info()['user'] == 'Admin') {
  qaelpath <- 'C:/Users/Admin/Deakin University/QAEL - WERP in house - WERP'
} else {
  rlang::abort("YOU'RE NOT GALEN. PUT IN YOUR PATH TO QAEL-WERP")
}

# python can't use the tildes, so have to expand
qaelpath <- path.expand(qaelpath)

# Outer directory for project data
project_dir = file.path(qaelpath, 'Toolkit', 'macquarie')

# module_output
ewr_results <- c('module_output', 'EWR') 
econimic_results <- c('module_output', 'Economic') 
  
  
# outputs of aggregator. There may be multiple modules
agg_results <- c('aggregator_output','sdl_EWRs')
aggregations <-  c('sdl_EWRs', 'sdl_objective', 'sdl_objective_simple','sdl_target' , 'sdl_theme')

comp_results <- file.path(project_dir, 'comparer_output') 


# #DATA PATHS - by data type
  #hydro_paths <- list.files(hydro_dir_historical,  pattern="*Straight Node*", full.names=TRUE, recursive = TRUE)
  #balance_paths <- list.files(hydro_dir_historical,  pattern="*h2o_table.nc", full.names=TRUE, recursive = TRUE)
  #total_licvol_paths <- list.files(hydro_dir_historical,  pattern="*total_licvol.csv", full.names=TRUE, recursive = TRUE)
  economic_paths <- file.path(project_dir, 'module_output', 'Economic', "Combined_data.xlsx")
  
# #DATA PATHS - by Mk
#   hydro_paths <- list.files(hydro_dir_Mk5,  pattern="*Straight Node*", full.names=TRUE, recursive = TRUE)
#   balance_paths <- list.files(hydro_dir_Mk5,  pattern="*h2o_table.nc", full.names=TRUE, recursive = TRUE)
#   total_licvol_paths <- list.files(hydro_dir_Mk5,  pattern="*total_licvol.csv", full.names=TRUE, recursive = TRUE)
    
  
```

# Economic results

```{r}
#economic_paths
length(readxl::excel_sheets(economic_paths))


read_plus_xl <- function(flnm, sheet) {
    readxl::read_excel(flnm, sheet = sheet) |>
    dplyr::mutate(filename = flnm, sheet = sheet)
}

Merged_economic_historic <- tibble::tibble()
Merged_economic_stochastic <- tibble::tibble()

#economic data
#HISTORIC:
for (i in 1:length(economic_paths)) {
  for (j in 2:4) {

Merged_economic <- do.call(rbind,
          lapply(economic_paths[i], sheet = j, read_plus_xl))

Merged_economic_hold <- Merged_economic[-(1:2),c("filename", "sheet")]

Merged_economic$filename <- NULL
Merged_economic$sheet <- NULL

colnames(Merged_economic) <- Merged_economic[2,]
Merged_economic <- Merged_economic[-(1:2),-c(1,3,10:13)]
Merged_economic <- tibble::tibble(cbind(Merged_economic, Merged_economic_hold)) 
Merged_economic_hold <- NULL
Merged_economic <- Merged_economic |>
  dplyr::rename(year = Total_Macquarie) |>
  dplyr::mutate(SWSDLName = "Macquarie–Castlereagh") |>
  tidyr::pivot_longer(cols = 2:7, names_to = "shok_scenario", values_to = "economic_benefit")|>
  tidyr::separate(shok_scenario, sep = "_", remove = FALSE, into = c("shok_climate","shok_adaptation"))|>
  dplyr::mutate(Data = "Historic",
                shok_replicate = "ensemble_1")
  
Merged_economic_historic <- dplyr::bind_rows(Merged_economic_historic, Merged_economic)
Merged_economic <- NULL
  }
  }
  
#STOCHASTIC:
for (i in 1:length(economic_paths)) {
  for (j in 5:8) { #length(readxl::excel_sheets(economic_paths[1]))

Merged_economic <- do.call(rbind,
          lapply(economic_paths[i], sheet = j, read_plus_xl))

Merged_economic_hold <- Merged_economic[-(1:2),c("filename", "sheet")]
Merged_economic_hold_scenario <- colnames(Merged_economic)

Merged_economic$filename <- NULL
Merged_economic$sheet <- NULL

colnames(Merged_economic) <- c("shok_delete","year", "shok_NA", Merged_economic[2,-1:-3])
Merged_economic <- Merged_economic[-(1:2),-c(1,3,10:13)]
Merged_economic <- tibble::tibble(cbind(Merged_economic, Merged_economic_hold)) 
Merged_economic_hold <- NULL
Merged_economic <- Merged_economic |>
  #dplyr::rename(year = Total_Macquarie) |>
  dplyr::mutate(SWSDLName = "Macquarie–Castlereagh") |>
  tidyr::pivot_longer(cols = 2:73, names_to = "shok_replicate", values_to = "economic_benefit")|>
  dplyr::mutate(shok_climate = Merged_economic_hold_scenario[2],
                shok_adaptation = "Quo",
                Data = "Stochastic")
  
Merged_economic_stochastic <- dplyr::bind_rows(Merged_economic_stochastic, Merged_economic)
Merged_economic <- NULL
  }
  }

Merged_economic_init <- dplyr::bind_rows(Merged_economic_historic, Merged_economic_stochastic)
```


```{r}
Merged_economic_data <- Merged_economic_init  |>
  dplyr::mutate(date = as.Date(paste0(as.character(year), '-07-01')))|>
  tidyr::separate(shok_replicate, sep = "_", remove = FALSE, into = c("shok_ensemble","replicate"))|>
  dplyr::mutate(replicate = as.character(as.numeric(replicate)-1))|>
  dplyr::mutate(names_CSIRO_climate_scenario = dplyr::case_when(shok_climate == "Base" ~ "Historical climate",
                                                  shok_climate == "Base (Historical)" ~ "Historical climate",              
                                                  shok_climate == "HotDry"  ~ "Hot and Dry",
                                                  shok_climate == "JustHot"  ~ "Just Hot",
                                                  shok_climate == "HotWet"  ~ "Hot and Wet",
                                                  shok_climate == "JustDry"  ~ "Just Dry",
                                                  shok_climate == "JustWet"  ~ "Just Wet"))|>
  dplyr::mutate(names_CSIRO_climate_scenario = factor(names_CSIRO_climate_scenario, 
           levels = c("Just Wet", "Hot and Wet", "Historical climate", "Just Hot", "Just Dry", "Hot and Dry")))|>  
  dplyr::mutate(licvolfactor = dplyr::case_when(shok_adaptation == "Quo" ~ 0.0,
                                    shok_adaptation == "Sal"  ~ 0.5,
                                    shok_adaptation == "Pur"  ~ 1.5)) |>
  dplyr::mutate(Evapotranspiration = dplyr::case_when(names_CSIRO_climate_scenario == "Historical climate"  ~ 1,
                                                  names_CSIRO_climate_scenario == "Hot and Dry" ~ 1.07,
                                                  names_CSIRO_climate_scenario == "Just Hot" ~ 1.07,
                                                  names_CSIRO_climate_scenario == "Hot and Wet" ~ 1.07,
                                                  names_CSIRO_climate_scenario == "Just Dry" ~ 1,
                                                  names_CSIRO_climate_scenario == "Just Wet" ~ 1))|>
  dplyr::mutate(Rainfall = dplyr::case_when(names_CSIRO_climate_scenario == "Historical climate"  ~ 1,
                                                  names_CSIRO_climate_scenario == "Hot and Dry" ~ 0.8,
                                                  names_CSIRO_climate_scenario == "Just Hot" ~ 1,
                                                  names_CSIRO_climate_scenario == "Hot and Wet" ~ 1.2,
                                                  names_CSIRO_climate_scenario == "Just Dry" ~ 0.8,
                                                  names_CSIRO_climate_scenario == "Just Wet" ~ 1.2))|>
  dplyr::mutate(Mk = "Mk4a")|>
  dplyr::select(-contains("shok_"))



write.csv(Merged_economic_data, file = file.path(project_dir, 'module_output', 'Economic', "Economic_yearly.csv"))

```

## Temporary aggregator

```{r}

Merged_economic_summary <- Merged_economic_data |>
  dplyr::group_by(filename, sheet, SWSDLName, names_CSIRO_climate_scenario, licvolfactor, Evapotranspiration, Rainfall, Mk, Data, replicate) |>
  dplyr::summarise(economic_benefit = mean(as.numeric(economic_benefit)))

write.csv(Merged_economic_summary, file = file.path(project_dir, 'module_output', 'Economic', "Economic_summary.csv"))
  
```
