---
title: "Run EWRs"
format: html
editor: visual
---

```{r}
library(werptoolkitr)
library(dplyr)
library(sf) # Needed? I think not here, but just in case
library(future)

# set the future plan for parallelising.
plan(multisession)
```

## Paths

I'm going to set this up to dump data to the QAEL WERP share for now. Unfortunately, that calls itself something different for each of us.

```{r}
if (Sys.info()['user'] == 'galen') {
  qaelpath <- '~/../Deakin University/QAEL - WERP in house - WERP'
} else {
  rlang::abort("YOU'RE NOT GALEN. PUT IN YOUR PATH TO QAEL-WERP")
}
```

```{r}
# python can't use the tildes, so have to expand
qaelpath <- path.expand(qaelpath)

# Outer directory for project data
project_dir = file.path(qaelpath, 'Toolkit', 'macq-data')

# Hydrographs (expected to exist already; created here with Ash_data_sorting.qmd)
hydro_dir = file.path(project_dir, 'river_system_simulation_data')

# Generated data
# EWR outputs (will be created here in controller, read from here in aggregator)
ewr_results <- file.path(project_dir, 'module_output', 'EWR')

# outputs of aggregator. There may be multiple modules
agg_results <- file.path(project_dir, 'aggregator_output')
```

## Module controls

We need 'summary' and 'yearly' to assess EWR achievement. No reason to return them to the session.

```{r}
outputType <- list('summary', 'yearly')
returnType <- list('none') # list('summary', 'yearly')
```

# Run EWR tool

Run it in parallel, and use the 'IQQM - netcdf\` format. (and note timing)

```{r}


ewr_time <- system.time(ewr_out <- prep_run_save_ewrs(hydro_dir = hydro_dir, 
                                  output_parent_dir = project_dir,
                              model_format = 'IQQM - netcdf',
                                  outputType = outputType,
                                  returnType = returnType,
                              rparallel = TRUE))
```

The timing

```{r}
glue::glue("The run of all files through the EWR took {ewr_time['elapsed']} seconds, which is
           {ewr_time['elapsed']/60} minutes, which is
           {ewr_time['elapsed']/60/60} hours")
```

1.8 hours for the first run
