[tool.poetry]
name = "tuse"
version = "0.1.0"
description = ""
authors = ["Galen Holt <53928785+galenholt@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
py-ewr = {git = "https://github.com/MDBAuth/EWR_tool.git", rev = "GalenH"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
