[tool.poetry]
name = "hydrobot"
version = "0.1.0"
description = ""
authors = ["Galen Holt <53928785+galenholt@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
py-ewr = {git = "https://github.com/MDBAuth/EWR_tool.git", rev = "8cd3ebc904935ac2bf2df737e6fab28b20e6fa5c"}
setuptools = "^80.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
